
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: band_site_development

test:
  <<: *default
  database: band_site_test

production:
  <<: *default
  database: band_site_production
  username: band_site
  password: <%= ENV["BAND_SITE_DATABASE_PASSWORD"] %>
